version: '3.8'

services:
  app:
    build: .
    image: ximegasub/python-flask-kb8:0.5
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 32000:3306
    volumes:
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myappdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  